### ISSUE TITLE
Matlab R2022a Undefined function medfilt2

### ISSUE THREAD

**Issue by manuelbauer1603** [david-brinkmeier/fokuspokus#1]
On Test/Single Shot throws
![grafik](https://user-images.githubusercontent.com/47754011/167469279-1799989e-6192-4dcf-a563-aba4cf73a1c1.png)

**Comment by manuelbauer1603** [comment]
was missing Image Processing Toolbox

**Comment by david-brinkmeier** [comment]
thanks for the heads up! I'll put in a warning if image processing toolbox is missing and disable medfilt there
